site_name: SICOIM
site_url: https://manuales.algoritmia.sv/sicoim/
site_description: Manual de usuario de SICOIM
site_author: Edwin Fajardo
copyright: Copyright &copy;2024 Algoritmia SV
site_dir: /store/bphp/manuals/sicoim
nav:
  - Inicio: index.md
  - Usuario: usuario.md
  - Cuentas corrientes:
    - Recibos: cuentas-corrientes/recibos.md
    - Avisos de cobro: cuentas-corrientes/avisos-de-cobro.md
    - Constancias: cuentas-corrientes/constancias.md
    - Solvencias: cuentas-corrientes/solvencias.md
    - Numeraciones: cuentas-corrientes/numeraciones.md
  - Catastro:
    - Contribuyentes: catastro/contribuyentes.md
    - Inmuebles: catastro/inmuebles.md
    - Empresas: catastro/empresas.md
    - Mercados: catastro/mercados.md
    - Antenas y postes: catastro/antenas-y-postes.md
    - Cementerios: catastro/cementerios.md
    - Vallas publicitarias: catastro/vallas-publicitarias.md
    - Sectores: catastro/sectores.md
  - Recuperación de mora:
    - Mora inmuebles: recuperación-de-mora/mora-inmuebles.md
    - Mora empresas: recuperación-de-mora/mora-empresas.md
  - Caja:
    - Canasta de recibos: caja/canasta-recibos.md
    - Ingresos diarios: caja/ingresos-diarios.md
    - Cajas: caja/cajas.md
  - Herramientas:
    - 'Historial de actividades': herramientas/historial-actividades.md
    - 'Papelera de reciclaje': herramientas/papelera.md
  - Configuraciones:
    - 'Datos de la empresa': configuraciones/entidad.md
    - Preferencias: configuraciones/preferencias.md
    - Roles: configuraciones/roles.md
    - Usuarios: configuraciones/usuarios.md
theme:
  name: material
  nav_style: dark
  locale: es
extra_css:
  - css/algoritmiasv.css
markdown_extensions:
  - attr_list
